# PVC - necesito una plaza de X tamaño con estas características
# Kubernetes busca un PV que encaje y los vincula
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi